export interface AccountInterface{
	id?:string;
	numberAccount?:string;
	numberBankAccount?:string;
	name?:string;
	phone?:string;
	email?:string;
	subjectEmail?:string;
	bankEntity?:string;
	adminEmail?:string;
	status?:string;
	message?:string;
	type?:string;
	address?:string;
	usertype?:string;
	userId?:string;
	fullProfile?:boolean;
	images?:Array<string>;
}